### ISSUE TITLE
Integrate Cloudkit into Draft UI

### ISSUE THREAD

**Issue by CaioFaSoares** [bubble-jam-organization/bubble-jam#55]

**Comment by CaioFaSoares** [comment]
@ThiagoHBA 

Aparentemente modificationDate não é sortable, ou seja, a query `query.sortDescriptors = [NSSortDescriptor(key: "modificationDate", ascending: true)]` sempre retornará um erro.
Quando o usuário já tem uma Jam no CK, outra é apendada ou o asset é subsitituido? se for apendado, talvez seja possível só passar modTable junto da query utilizando `.last` ou `.first`.

![image](https://user-images.githubusercontent.com/51139215/221392087-65653c49-93d8-4f8e-8956-11c7543a3590.png)

**Comment by ThiagoHBA** [comment]
Ele é apendado, mas o lance do modificationDate ser sortable ou não é fácil de resolver, é só uma configuração que a gente faz no atributo lá no console, esqueci que precisava disso
